# Generated by Django 2.2.7 on 2019-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.TextField(default='roomtype')),
                ('light_status', models.IntegerField(default='light_status')),
                ('temperature_degree', models.FloatField(default='temperature_degree')),
                ('thermostat_status', models.TextField(default='thermostat_status')),
            ],
            options={
                'db_table': 'home_automation',
            },
        ),
    ]
