# Generated by Django 2.2.7 on 2019-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_automation',
            name='light_status',
            field=models.IntegerField(default='light_status', null=True),
        ),
        migrations.AlterField(
            model_name='home_automation',
            name='temperature_degree',
            field=models.FloatField(default='temperature_degree', null=True),
        ),
        migrations.AlterField(
            model_name='home_automation',
            name='thermostat_status',
            field=models.TextField(default='thermostat_status', null=True),
        ),
    ]
